### ISSUE TITLE
Standardise project's folder structure

### ISSUE THREAD

**Issue by vladimino** [MagedAhmad/PHP-microframework#13]
In the PHP world, there are some conventions on how a good package must be structured. Although none are official, following them is a good practice as it makes it much easier for other developers to understand the purpose of each folder just by looking into the root of the project.

Currently, I have no idea what is the difference between `app`, `code` and `src` folders within the project.  Some of the files are also placed into the root level (e.g. `project.php`) which makes it even more confusing.

I'd recommend updating the structure according to [Symfony recommendations](https://symfony.com/doc/current/best_practices.html#use-the-default-directory-structure) because it is most common now. If you need my help with what should go where I'll be happy to suggest.

**Comment by vladimino** [comment]
@MagedAhmad , FYI: I am waiting for this issue to be closed before I'll give more specific comments about the source code.

**Comment by MagedAhmad** [comment]
@vladimino this issue should be closed a few days ago, i'm stuck with a silly problem, you can find it [here ](https://stackoverflow.com/questions/58788786/style-and-js-doesnt-work-after-changing-project-entry-point-to-public-folder) .

**Comment by vladimino** [comment]
@MagedAhmad thanks for heads up, answered to you over there 😄
